version: "3.3"

services:
    openldap:
        build: .
        command: ldap
        restart: on-failure:5
        mem_limit: 256M
        mem_reservation: 100M
        #volumes:
        #  - ./tests/data/db.sqlite:/data/db.sqlite
        healthcheck:
            test: 'ldapwhoami -D "cn=$${DOCKER_LDAP_HEALTHCHECK_USERNAME}" -w "$${DOCKER_LDAP_HEALTHCHECK_PASSWORD}"'
            start_period: 5s
            interval: 10s
            timeout: 5s
            retries: 3
        environment:
            # 256 to enable debug
            # See: https://www.openldap.org/doc/admin24/slapdconf2.html
            LDAP_LOG_LEVEL: 0
            LDAP_OPENLDAP_GID: 0
            LDAP_OPENLDAP_UID: 0
            LDAP_BASE_DN: "dc=example,dc=org"
            LDAP_AUTH_BASE_DN: "ou=people,dc=example,dc=org"
            LDAP_ADMIN_PASSWORD: "{SSHA}uFcXuY+bFdxQZktdAR2l163q6KR3Nc5e"
            LDAP_CONFIG_PASSWORD: "{SSHA}V0MnvygRbzo3hg33X2DxycAxO5SvuOM5"
            LDAP_MONITOR_PASSWORD: "{SSHA}1h+K1VIdptHytwoqDd+z+ozORIKmGvG3"
            # Only used by healthcheck command defined above
            DOCKER_LDAP_HEALTHCHECK_USERNAME: monitor
            DOCKER_LDAP_HEALTHCHECK_PASSWORD: monitor
            # SSL setting
            LDAP_TLS_CA_CRT_FILENAME: "/data/ca.pem"
            LDAP_TLS_CRT_FILENAME: "/data/server-cert.pem"
            LDAP_TLS_KEY_FILENAME: "/data/server-key.pem"
            LDAP_TLS_CIPHER_SUITE: "HIGH:MEDIUM:-SSLv2"
            # never | allow | try | demand
            LDAP_TLS_VERIFY_CLIENT: "try"
            # Add ldaps:/// to SSL listen
            LDAP_LISTEN_URLS: "ldap:/// ldapi:/// ldaps:///"
        volumes:
          - ./tests/data/ldap.server.intranet_ca.cer:/data/ca.pem:ro
          - ./tests/data/ldap.server.intranet.cer:/data/server-cert.pem:ro
          - ./tests/data/ldap.server.intranet.key:/data/server-key.pem:ro

    sut:
        depends_on:
            openldap:
                condition: service_healthy
        build: .
        volumes:
          - ./tests/:/tests:ro
          - ./tests/data/ldap.server.intranet_ca.cer:/data/ca.pem:ro
        entrypoint: /tests/run.sh
        environment:
            LDAPTLS_CACERT: /data/ca.pem
            LDAPTLS_REQCERT: hard
