name: Build docker image

on: [push]

jobs:
    build-action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Build image
              run: make docker-build
            - name: Test image
              run: make test
